name: Build

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--mac"
          - platform: "ubuntu-22.04"
            args: "--linux"
          - platform: "windows-latest"
            args: "--win"
    runs-on: ${{ matrix.platform }}
    steps:
          - uses: actions/checkout@v4
          - name: Install Node.js
            uses: actions/setup-node@v4
            with:
              node-version: 20
          - name: Install dependencies
            run: npm i
          - name: Build Vite App
            run: npm run build:all
          - name: Debug
            run: |
                echo "Contents of dist-electron:"
                ls -la dist-electron/ || echo "dist-electron directory not found"
                echo "Contents of dist:"
                ls -la dist/ || echo "dist directory not found"
          - name: Build Electron App
            run: npx electron-builder ${{ matrix.args }}
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: Upload Artifacts
            uses: actions/upload-artifact@v4
            with:
              name: release-${{ matrix.platform }}
              path: |
                release/*.dmg
                release/*.exe
                release/*.AppImage
                release/*.msi
